name = "ice-scout-api"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-10-22"
main = "src/index.ts"

[[d1_databases]]
binding = "DB"
database_name = "ice-scout-db"
database_id = "156193ef-d400-4968-9c70-4a730b3e1449"

[observability]
enabled = true
head_sampling_rate = 1
